name: money_manager
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  dart_either: ^1.0.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  injectable: ^2.4.4
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/error.json
