name: money_manager
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dart_either: ^1.0.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  intl: ^0.19.0
  lottie: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/error.json
