name: money_manager
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  dart_either: ^1.0.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_slidable: ^3.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  google_sign_in: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.19.0
  lottie: ^3.1.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/error.json
